/*
 * Regenerates catalog.generated.ts from the live Munich citizen API.
 *
 *   bun run generate:catalog
 *
 * Standalone (no imports from the typed client) so it can run even when the
 * generated file is missing or stale. Honours MUC_PROXY_URL / HTTPS_PROXY.
 */

import { writeFileSync } from "node:fs";

const API_BASE = process.env.API_BASE || "https://www48.muenchen.de/buergeransicht/api/citizen";
const proxy = process.env.MUC_PROXY_URL || process.env.HTTPS_PROXY || undefined;

interface RawService {
  id: number;
  name: string;
}
interface RawOffice {
  id: number;
  name: string;
  address?: { street?: string; house_number?: string };
}
interface RawRelation {
  officeId: number;
  serviceId: number;
  public: boolean;
}
interface OfficesAndServices {
  services: RawService[];
  offices: RawOffice[];
  relations: RawRelation[];
}

async function main(): Promise<void> {
  const init: RequestInit & { proxy?: string } = { headers: { Accept: "application/json" } };
  if (proxy) init.proxy = proxy;

  const res = await fetch(`${API_BASE}/offices-and-services/`, init);
  if (!res.ok) throw new Error(`offices-and-services HTTP ${res.status}`);
  const data = (await res.json()) as OfficesAndServices;

  const services = [...data.services].sort((a, b) => a.id - b.id);
  const offices = [...data.offices].sort((a, b) => a.id - b.id);
  const serviceIds = new Set(services.map((s) => s.id));
  const officeIds = new Set(offices.map((o) => o.id));

  // Group public relations (service -> sorted, de-duplicated office IDs),
  // keeping only IDs that exist in both canonical lists.
  const serviceOffices = new Map<number, Set<number>>();
  for (const r of data.relations) {
    if (!r.public || !serviceIds.has(r.serviceId) || !officeIds.has(r.officeId)) continue;
    if (!serviceOffices.has(r.serviceId)) serviceOffices.set(r.serviceId, new Set());
    serviceOffices.get(r.serviceId)!.add(r.officeId);
  }

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by generate-catalog.ts — do not edit by hand.");
  lines.push("// Refresh with: bun run generate:catalog");
  lines.push(`// Source: ${API_BASE}/offices-and-services/`);
  lines.push(`// Generated: ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");

  lines.push("export const SERVICES = [");
  for (const s of services) lines.push(`  { id: ${s.id}, name: ${JSON.stringify(s.name)} },`);
  lines.push("] as const;");
  lines.push("");

  lines.push("export const OFFICES = [");
  for (const o of offices) {
    const street = o.address?.street ?? "";
    const houseNumber = o.address?.house_number ?? "";
    lines.push(
      `  { id: ${o.id}, name: ${JSON.stringify(o.name)}, street: ${JSON.stringify(street)}, houseNumber: ${JSON.stringify(houseNumber)} },`,
    );
  }
  lines.push("] as const;");
  lines.push("");

  lines.push("/** Office IDs that publicly offer each service. */");
  lines.push("export const SERVICE_OFFICES = {");
  for (const sid of [...serviceOffices.keys()].sort((a, b) => a - b)) {
    const offs = [...serviceOffices.get(sid)!].sort((a, b) => a - b);
    lines.push(`  ${sid}: [${offs.join(", ")}],`);
  }
  lines.push("} as const;");
  lines.push("");

  writeFileSync(new URL("../libs/catalog.generated.ts", import.meta.url), lines.join("\n"));
  console.log(
    `Wrote libs/catalog.generated.ts: ${services.length} services, ${offices.length} offices, ${serviceOffices.size} with a public office.`,
  );
}

main().catch((e: unknown) => {
  console.error("generate-catalog failed:", e instanceof Error ? e.message : e);
  process.exit(1);
});
